(defun insert-time ()
   (interactive)
   (insert (format-time-string "%Y-%m-%dT%H:%M:%S")))
(defun insert-date ()
   (interactive)
   (insert (format-time-string "%Y-%m-%d")))
(defun show-file-name ()
  "Show the full path file name in the minibuffer."
  (interactive)
  (message (buffer-file-name))
  (kill-new (file-truename buffer-file-name))
)
